### ISSUE TITLE
Basic Use Question

### ISSUE THREAD

**Issue by braebo** [o2dazone/svelte-music-player#6]
How might I go about populating the index.json (not sure what format / location to store the audio)?

Keen to check this out!

**Comment by o2dazone** [comment]
Hey @FractalHQ,

Thanks for the interest! This project is split into two pieces. `svelte-music-player` is the frontend. And then I have a small package (That I've sent you an invite to) that does the indexing. It's a little barebones for now because it's a personal project, so feel free to email me (this name at gmail) if you have any questions.

Thanks!

**Comment by braebo** [comment]
Awesome, thank you man!  Really kind of you to do that.  Much appreciated :)
